### PR TITLE
add power series coefficient calculation document

### PR DESCRIPTION
**Pull request by matthewm8m**

### CODE REVIEW

**Comment by bkappes** [comment]
@MatthewM8M,

Instead of your derivation living in its own, separate document, can you please drop that into the discussion section?

**Comment by matthewm8m** [comment]
@bkappes Done!

**Comment by bkappes** [comment]
Thanks, Matt!

**Comment by bkappes** [comment]
The derivation in **Scalar Transformation** begins by supposing $x \in \mathbb{R}$, but that is not a supposition we can make. (In fact, it directly contravenes the assumptions made in equations 15, 16 and others.)

Additionally, the term in the equation immediately before Section 5.3 (there is no equation number...),
\begin{align}
y &= \sum_{k=0}^{\infty} s_k \left( \theta^k \sum_{n=0}^{\infty} a_n z^n \right)^k
   &\neq \sum_{k=0}^{\infty} s_k \theta^k \left( \sum_{n=0}^{\infty} a_n z^n \right)^k
\end{align}

Additionally, 
$$
\left( \sum_{n=0}^{\infty} a_n z^n \right)^k \neq \sum_{k+0 + k_1 + k_2 + \cdots = k} \binom{k}{k_0, k_1, k_2, \ldots} \prod_{n=0}^{\infty} (a_n z^n)^{k_n}
$$

instead,

$$
\left( \sum_{n=0}^{\infty} a_n z^n \right)^k = \sum_{k+0 + k_1 + k_2 + \cdots = k} \binom{k}{k_0, k_1, k_2, \ldots} \prod_{n=0}^{k} (a_n z^n)^{k_n}
$$

This has knock-on effects throughout the rest of the derivation.

**Comment by matthewm8m** [comment]
@bkappes I've left in a scalar derivation ($x \in \mathbb{R}$) in for us to discuss. We can remove it in the final paper or frame it as a special case of the vector derivation.

I've checked the first equation you mentioned. It is correct because $\theta \in \mathbb{R}$.
I've also checked the second equation and my derivation is correct according to the [Multinomial Theorem](https://en.wikipedia.org/wiki/Multinomial_theorem) (where $m = \infty$ and $n = k$).

We can discuss this further in our meeting.

**Pull request merged**
